on: push

name: Build Node

jobs:
  build:
    name: Build Node
    runs-on: ubuntu-latest
    container:
      image: node:10.5.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: |
          git fetch --prune --unshallow --tags

      - name: Copy source
        run: |
          cp design/ui/vue.config.js.build design/ui/vue.config.js

      - name: Compile sources
        run: |
          cd design/ui
          npm install
          npm run build

      - name: Upload Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: compiled-node
          path: ./apps/core/static/
